const capabilities = [
    { category: 'Voz', name: 'Despertar a Jarvis', description: 'Sale del modo descanso y comienza a aceptar órdenes.', command: 'Jarvis, prendete' },
    { category: 'Voz', name: 'Poner en descanso', description: 'Ignora todas las órdenes salvo la frase para despertar.', command: 'Jarvis, apagate' },
    { category: 'Asistente', name: 'Conversar y consultar', description: 'Responde preguntas generales usando el modo activo.', command: 'Jarvis, explicame [tema]' },
    { category: 'Asistente', name: 'Buscar información actual', description: 'Consulta noticias, clima, dólar, cripto o deportes.', command: 'Buscá en internet [consulta]' },
    { category: 'Sistema', name: 'Abrir una aplicación', description: 'Abre una app instalada o un servicio web.', command: 'Abrí [aplicación]' },
    { category: 'Sistema', name: 'Enseñar un comando', description: 'Asocia una frase personalizada con una aplicación.', command: 'Cuando te diga [frase], abrí [aplicación]' },
    { category: 'Comunicación', name: 'Enviar WhatsApp', description: 'Envía un mensaje mediante el motor de automatización.', command: 'Enviá por WhatsApp a [contacto]: [mensaje]' },
    { category: 'Comunicación', name: 'Enviar correo', description: 'Envía un email mediante el motor de automatización.', command: 'Enviá un correo a [destinatario]: [mensaje]' },
    { category: 'Agenda', name: 'Programar recordatorio', description: 'Agenda una notificación, mensaje o apertura de app.', command: 'Recordame a las [HH:MM] [tarea]' },
    { category: 'Agenda', name: 'Revisar recordatorios', description: 'Muestra las tareas locales y externas pendientes.', command: 'Mostrame mis recordatorios' },
    { category: 'Agenda', name: 'Borrar recordatorios', description: 'Elimina todas las alarmas locales pendientes.', command: 'Borrá todos los recordatorios' },
    { category: 'Contenido', name: 'Crear documento', description: 'Genera Word, Excel, PowerPoint o PDF.', command: 'Creá un [Word/Excel/PowerPoint/PDF] sobre [tema]' },
    { category: 'Contenido', name: 'Crear software', description: 'Construye o modifica una web, app o proyecto.', command: 'Creá una aplicación que [requisitos]' },
    { category: 'Contenido', name: 'Crear prompt técnico', description: 'Genera una arquitectura detallada para software.', command: 'Creá un prompt de software para [objetivo]' },
    { category: 'Imágenes', name: 'Generar imagen', description: 'Crea una imagen nueva con Stable Diffusion.', command: 'Generá una imagen de [descripción]' },
    { category: 'Imágenes', name: 'Editar imagen', description: 'Edita la imagen cargada y la zona marcada.', command: 'Editá esta imagen: [cambio]' },
    { category: 'Multimedia', name: 'Buscar película o serie', description: 'Busca contenido y abre Stremio.', command: 'Buscá en pelis [título]' },
    { category: 'Multimedia', name: 'Descargar multimedia', description: 'Descarga video o audio desde una URL compatible.', command: 'Descargá [URL]' },
    { category: 'Multimedia', name: 'Reproducir Spotify', description: 'Abre Spotify o reproduce una búsqueda si está conectado.', command: 'Poné [tema o artista] en Spotify' },
    { category: 'Modos', name: 'Mostrar modos', description: 'Presenta los modos de comportamiento disponibles.', command: 'Mostrar modos' },
    { category: 'Modos', name: 'Activar modo', description: 'Cambia el comportamiento y modelo activos.', command: 'Activar modo [nombre]' },
    { category: 'Modos', name: 'Crear modo', description: 'Abre el formulario para añadir un modo.', command: 'Crear modo' },
    { category: 'Contexto', name: 'Activar observador', description: 'Registra cambios de ventana para aportar contexto.', command: 'Activar observador' },
    { category: 'Contexto', name: 'Desactivar observador', description: 'Detiene por completo el sondeo de ventanas.', command: 'Desactivar observador' },
    { category: 'Seguridad', name: 'Entrenar biometría', description: 'Registra el rostro y configura un PIN de respaldo.', command: 'Entrenar seguridad [PIN de 4 dígitos]' },
    { category: 'Seguridad', name: 'Activar escudo', description: 'Inicia la protección biométrica residente.', command: 'Activar seguridad' },
    { category: 'Seguridad', name: 'Desactivar escudo', description: 'Apaga la protección y sus procesos residentes.', command: 'Desactivar seguridad' },
    { category: 'Extensiones', name: 'Aprender habilidad', description: 'Crea una habilidad Python para una tarea nueva.', command: 'Quiero que aprendas a [tarea]' }
];

module.exports = capabilities;
